# version: 2
# updates:
#   - package-ecosystem: 'npm'
#     directory: '/'
#     schedule:
#       interval: 'weekly'
#       day: 'thursday'
#       time: '11:00'
#       timezone: 'Europe/Belgrade'
#     versioning-strategy: increase
#     ignore:
#       - dependency-name: '*'
#         update-types: ['version-update:semver-patch']
