name: upload coverage

on:
  push:
    branches: ['master']

defaults:
  run:
    shell: bash

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare actions
        uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Collect coverage
        run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
    timeout-minutes: 5
